[package]
name = "js-x-ray-wasm"
description = "WASM bindings for the js-x-ray JavaScript AST analysis library"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
js-x-ray = { path = "../js-x-ray", default-features = false }
serde_json.workspace = true
wasm-bindgen = "0.2"
